### ISSUE TITLE
Manipulate with arrays

### ISSUE THREAD

**Issue by qawsed55** [tobi01001/LED_Stripe_Dynamic_web_conf#17]
Hello. May be someone can tell me how I can change pixel order in this project?
I have setup, where lighting algorithm need to draw not 1-2-3-4-5-...-NUM_LEDS, but in other order (5-3-6-1-2-8-...).
May be you can say - where I need to paste order changing function?
Example:
```
const uint8_t otherOrder[NUM_LEDS] = { 106, 89, 209, 47, 166, 154, 50, 217, 75, 116, 200, 33} 
...

 for (uint8_t i = 0; i < NUM_LEDS; i++) {
    uint8_t j = otherOrder[i];
    leds[j] = someRenderingFunct();
  }
```
Thanks!

**Comment by tobi01001** [comment]
Ahhh, I never thought about that because currently my order is just straight forward.

Anyway, best place to do this (easily) is probybly directly before writing the leds.
The code repo (and the project) became a bit messy lately. 

In order to keep switching between Effects and on/off quite smooth, I already implemented a second array of LED Data.

You cuold map your arrangement by replacing this line:
https://github.com/tobi01001/LED_Stripe_Dynamic_web_conf/blob/96211acd3edcf5100cd3d8df6c28264786bf37f7/lib/WS2812FX/WS2812FX_FastLED.cpp#L474
with 
``` C
const uint16_t otherOrder[LED_COUNT] = { 106, 89, 209, 47, 166, 154, 50, 217, 75, 116, 200, 33} 
...
for (uint16_t i = 0; i < LED_COUNT; i++) {
      nblend(_bleds[otherOrder[i]], leds[i],l_blend);
}
```
Please note the uint16_t I used to ensure LED_COUNTs > 255 are possible....

Not 100% sure if this works but I do not see a particular reason why not... :-)

Let me know if that helps.

**Comment by qawsed55** [comment]
Tobi, thanks for reply. I'll try you code and write here does it work or not.
I need it because I want to implement your code for my setup: www.youtube.com/watch?v=PDc_siO9afY
In Jason's code - there are all I need, but there is no "blending" between procedures and I do not know how to make it ) Thats why I will make hard work to paste some pieces of code from that project to yours :smiley: I'm very bad programmer.
If you interested of phylotaxis math - In youtubes video "about" you can find link to cloud folder with many interesting books that I find in internet (in English too)

**Comment by qawsed55** [comment]
Your advice works good!

**Comment by tobi01001** [comment]
Closing as proposal seems to work.
